---
- name: Clone Odoo Docker Compose repository
  git:
    repo: "{{ compose_repo }}"
    dest: "{{ compose_dir }}"
    version: "17"
    update: true
    force: true     

- name: Copy custom addons to host
  copy:
    src: "{{ playbook_dir }}/custom-addons/"
    dest: "{{ custom_addons_path }}"
    mode: '0755'

- name: Create config directory
  file:
    path: "{{ compose_dir }}/config"
    state: directory
    mode: '0755'

- name: Copy Odoo configuration
  template:
    src: odoo.conf.j2
    dest: "{{ compose_dir }}/config/odoo.conf"
    mode: '0644'

- name: Create .env file
  template:
    src: .env.j2
    dest: "{{ compose_dir }}/.env"
    mode: '0644'

- name: Render docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ compose_dir }}/docker-compose.yml"

- name: Pull Docker Compose images via CLI
  command: docker-compose pull
  args:
    chdir: "{{ compose_dir }}"
  register: compose_pull
  failed_when: compose_pull.rc != 0 and compose_pull.rc != 1
  # rc=1 sometimes khi image up-to-date; adjust nếu cần

- name: Launch Odoo stack via Docker Compose CLI
  command: docker-compose up -d
  args:
    chdir: "{{ compose_dir }}"
